baseURL: https://leokr.fr
title: Léo Krebs
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: ''

params:
  image: /images/banner.png
  subtitle: IT engineer, casual photographer, old car restorer, and a few more.
  copyright: All rights reserved.
  author: Léo Krebs
  dontShowSource: true
  portfolio:
    columns:
      desktop:
        nature: 4
        archive: 6
        people: 2
        default: 3
      mobile:
        default: 2
        archive: 3
        people: 1
  socials:
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:leo@leokr.fr'
      landing: true
    - icon: 'fab fa-github fa-lg'
      url: https://github.com/Legoota
      landing: true
    - icon: 'fab fa-instagram fa-lg'
      url: 'https://www.instagram.com/legoo_k/'
    - icon: 'fab fa-linkedin-in fa-lg'
      url: 'https://www.linkedin.com/in/leokrebs/'
  homepage: "/home" # homepage link, mostly same with menu.main[0]
  specialPages:
    - home
    - archive
  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.
  plausible: ''
  disableRadius: false
  moveIt: false  # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  home: ":filename/"

menu:
  main:
    - name: home
      url: /home/
      weight: 1
    - name: people
      url: /tags/people/
      weight: 2
    - name: nature
      url: /tags/nature/
      weight: 3
    - name: archive
      url: /tags/archive/
      weight: 4
    - name: about
      url: /about/
      weight: 5
